language: java
jdk:
  - openjdk8
cache:
  directories:
    - "~/.m2"
deploy:
  provider: heroku
  app: methods-distance
  on:
    branch: master
  api_key:
    secure: QIaGqr+3eFwc5fi1UpBgGLQM+lsH7F0WdPWIhaceJJsjVpZawDnaJO25OQLBxD6FFlM/IL3KpQsb5vOdOwQUa52og4cCFoqFBd55FuI39hWSsUKPxe1+KfXdcXmrzHRmiHEPtVF+iPYlfNfS5duaXU6QStyRHiKB7hBStl2D7ftTOxwSzZ5BGUN8MrK4SeP2Y2bkxnluyIcWHrHmNXL42c41my5AdOPeOdo/CrVFL95xB5zLuw70xKg33Ro4YEnkabaTUEBRmQlg494LUXgxLv23Rw8TdyKdvtZfjc60oz0pSP7NosAFOnmKCWLZj8FWFzEw1b0vbHCLu3wOoPDqDM37Mp+rbStZC7qEtshNuFspq356SfnW45Xp4EeKOkIinGEz1LkDXEZpdSGtcy0N0ctfFs2A7tl4JWkTUo5sSB+NNaoM+QbO39WK/r1vTUt+c0SDI18mJd3jx61oA0SUj7GaUoLNDMPltGVHG1XUih6IfQM9FWPB4tXZHcv+cqy0fH17RfL8Qg0DydGBV8AkohI81lSbhzqmJGQSIMVu8Yn//0P6NSDga5pHRbH4kCpq4oljiela4d72McULrMLCGULMM+Pq9lviFOJWPkFJBYxsyoXgw9bg+NzJ1ACSN303nJPsVnS+lbGnN1la6LxxqaQeWDZFKfgetpBOPKu0MxQ=
notifications:
  email:
    on_success: never
    on_failure: never
