language: java
jdk:
  - oraclejdk8

cache:
  directories:
   - ~\.m2

deploy:
  provider: heroku
  app: methods-distance
  on:
    branch: master
  api_key:
    secure: qBsz+CHWl4r4cJkHQ2bO5DoiwYKPn4LKnyFO420b5Lt5ESC1ZsmI1+UUi+Fz5EzY0zJ4WwvuM4/fNG1jCkQj49RI708sMiHGKIegvswGr3VFf61Bg+oss1Bxc5FRC6jrqqH9Jq2buzrmfdSnDljSGWiaT9IBZWuQo4LkvIB7Do0fD94Vm/rQcEoxCeUXuXGsJ47YAAFlfirF3VvrBN+lS4/dgvr9PezPu9i50wr+bSt1/ciLP06N3Co6yBNeIqYMcuCpCzsb9nv74SxZnap4ggik6+5Vyx0X738gQDU7K8fOc4xfmoy8/uK7uucmTGdHWP6gd8WEZaM0WQbDj/rwwUG3oaeOBOHNrEbcU2ZpYjhDZBsiOX0iQJS490YhChMmEIjUCYjgJvPC0oQ0W8ILc0xKOX73ViIQk9ZY4eKzin23fFFgUllfd8G+/Pala5tOT6QIqjeDmzwBeEgMvLgnFqQ6KSxqAVGlppK6Tk8t3SVCL9wi4QQuUlhfOzXtOnz4n9cQYrFKSaBZotdc+4NsJmr/w4/ZNjVLftU04P+kvO+ZyioVsBpoBTVOpb4VUSCRAkN9KsWrwMMWHVOukDows4eeeB0E4rqRjsQigaNKWb2V5kRB3/FWS/p6sSxUHEBEcEgyrL6x5RZuxx7GZYCjtQVOoL4tDxYFDAS9xtlXzyM=

notifications:
  email:
    on_success: never
    on_failure: never
